# Configurazione Endpoint
rest.url=http://localhost:9000/api/prescrizioni
rest.content.type=application/json

rest.dataset.version=1.0
rest.mod=WS

# Timeout in secondi
rest.timeout=15

# Sicurezza
rest.auth.enabled=true
rest.token=abc123def456ghi789